AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/MixinUsage:
  Enabled: false